/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as HeaderRouteImport } from './routes/header'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MfoSlugRouteImport } from './routes/mfo.$slug'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderRoute = HeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MfoSlugRoute = MfoSlugRouteImport.update({
  id: '/mfo/$slug',
  path: '/mfo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/header': typeof HeaderRoute
  '/styleguide': typeof StyleguideRoute
  '/mfo/$slug': typeof MfoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/header': typeof HeaderRoute
  '/styleguide': typeof StyleguideRoute
  '/mfo/$slug': typeof MfoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/header': typeof HeaderRoute
  '/styleguide': typeof StyleguideRoute
  '/mfo/$slug': typeof MfoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/header' | '/styleguide' | '/mfo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/header' | '/styleguide' | '/mfo/$slug'
  id: '__root__' | '/' | '/header' | '/styleguide' | '/mfo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeaderRoute: typeof HeaderRoute
  StyleguideRoute: typeof StyleguideRoute
  MfoSlugRoute: typeof MfoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/header': {
      id: '/header'
      path: '/header'
      fullPath: '/header'
      preLoaderRoute: typeof HeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfo/$slug': {
      id: '/mfo/$slug'
      path: '/mfo/$slug'
      fullPath: '/mfo/$slug'
      preLoaderRoute: typeof MfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeaderRoute: HeaderRoute,
  StyleguideRoute: StyleguideRoute,
  MfoSlugRoute: MfoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
