/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as HeaderRouteImport } from './routes/header'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MfoIndexRouteImport } from './routes/mfo.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SummaSlugRouteImport } from './routes/summa.$slug'
import { Route as SituationsSlugRouteImport } from './routes/situations.$slug'
import { Route as MfoSlugRouteImport } from './routes/mfo.$slug'
import { Route as GorodaSlugRouteImport } from './routes/goroda.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderRoute = HeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MfoIndexRoute = MfoIndexRouteImport.update({
  id: '/mfo/',
  path: '/mfo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaSlugRoute = SummaSlugRouteImport.update({
  id: '/summa/$slug',
  path: '/summa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsSlugRoute = SituationsSlugRouteImport.update({
  id: '/situations/$slug',
  path: '/situations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MfoSlugRoute = MfoSlugRouteImport.update({
  id: '/mfo/$slug',
  path: '/mfo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GorodaSlugRoute = GorodaSlugRouteImport.update({
  id: '/goroda/$slug',
  path: '/goroda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/header': typeof HeaderRoute
  '/styleguide': typeof StyleguideRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/goroda/$slug': typeof GorodaSlugRoute
  '/mfo/$slug': typeof MfoSlugRoute
  '/situations/$slug': typeof SituationsSlugRoute
  '/summa/$slug': typeof SummaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/mfo/': typeof MfoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/header': typeof HeaderRoute
  '/styleguide': typeof StyleguideRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/goroda/$slug': typeof GorodaSlugRoute
  '/mfo/$slug': typeof MfoSlugRoute
  '/situations/$slug': typeof SituationsSlugRoute
  '/summa/$slug': typeof SummaSlugRoute
  '/blog': typeof BlogIndexRoute
  '/mfo': typeof MfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/header': typeof HeaderRoute
  '/styleguide': typeof StyleguideRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/goroda/$slug': typeof GorodaSlugRoute
  '/mfo/$slug': typeof MfoSlugRoute
  '/situations/$slug': typeof SituationsSlugRoute
  '/summa/$slug': typeof SummaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/mfo/': typeof MfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/header'
    | '/styleguide'
    | '/blog/$slug'
    | '/goroda/$slug'
    | '/mfo/$slug'
    | '/situations/$slug'
    | '/summa/$slug'
    | '/blog/'
    | '/mfo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/header'
    | '/styleguide'
    | '/blog/$slug'
    | '/goroda/$slug'
    | '/mfo/$slug'
    | '/situations/$slug'
    | '/summa/$slug'
    | '/blog'
    | '/mfo'
  id:
    | '__root__'
    | '/'
    | '/header'
    | '/styleguide'
    | '/blog/$slug'
    | '/goroda/$slug'
    | '/mfo/$slug'
    | '/situations/$slug'
    | '/summa/$slug'
    | '/blog/'
    | '/mfo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeaderRoute: typeof HeaderRoute
  StyleguideRoute: typeof StyleguideRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GorodaSlugRoute: typeof GorodaSlugRoute
  MfoSlugRoute: typeof MfoSlugRoute
  SituationsSlugRoute: typeof SituationsSlugRoute
  SummaSlugRoute: typeof SummaSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MfoIndexRoute: typeof MfoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/header': {
      id: '/header'
      path: '/header'
      fullPath: '/header'
      preLoaderRoute: typeof HeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfo/': {
      id: '/mfo/'
      path: '/mfo'
      fullPath: '/mfo/'
      preLoaderRoute: typeof MfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summa/$slug': {
      id: '/summa/$slug'
      path: '/summa/$slug'
      fullPath: '/summa/$slug'
      preLoaderRoute: typeof SummaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/$slug': {
      id: '/situations/$slug'
      path: '/situations/$slug'
      fullPath: '/situations/$slug'
      preLoaderRoute: typeof SituationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfo/$slug': {
      id: '/mfo/$slug'
      path: '/mfo/$slug'
      fullPath: '/mfo/$slug'
      preLoaderRoute: typeof MfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goroda/$slug': {
      id: '/goroda/$slug'
      path: '/goroda/$slug'
      fullPath: '/goroda/$slug'
      preLoaderRoute: typeof GorodaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeaderRoute: HeaderRoute,
  StyleguideRoute: StyleguideRoute,
  BlogSlugRoute: BlogSlugRoute,
  GorodaSlugRoute: GorodaSlugRoute,
  MfoSlugRoute: MfoSlugRoute,
  SituationsSlugRoute: SituationsSlugRoute,
  SummaSlugRoute: SummaSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  MfoIndexRoute: MfoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
